version: "3.7"

services:
  yarn:
    image: ${YARN_IMAGE:-mtsrus/hadoop:hadoop2-yarn}
    restart: no
    container_name: yarn
    hostname: yarn
    environment:
      WITH_JOBHISTORY_SERVER: "true"
    ports:
      - "9820:9820"   # HDFS IPC
      - "9870:9870"   # HDFS WebHDFS
      - "8088:8088"   # Yarn UI
      - "8042:8042"   # NodeManager UI
      - "19888:19888" # JobHistory UI
    volumes:
      - ./conf/hadoop/:/var/hadoop/conf/
      - hadoop-data:/var/hadoop/data/

volumes:
  hadoop-data:
